- const.go
add:
- add-known-secrets
- add-registry-acl-roles
- security-bootstrapper
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
> fix: add two constants and bootstrapper service

- const.go
This change restricts the new config options to security-secret-store and security-bootstrapper. It also adds gdoc for the new options.
> fix: restrict new config options to specific services

- const.go
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
> fix: typo in security-bootstrapper

- const.go
This commit adds support for a new security-secret-store config option, default-token-ttl. This setting can be used to increase (or decrease) the default TTL (one hour). If the TTL of a token expires before a service is started, the service will not be able to access the Secret Store.
> feat: add default-token-ttl config support

- utils.go
This PR fixes #10 by passing the snap name to syslog prefix including a `:hook` suffix.
> Pass snap name to syslog prefix

- .github/workflows/test.yml
- Makefile
- README.md
- snap/snapcraft.yaml
- utils_test.go
This PR supersedes #14.
It adds a snap for running the unit tests locally or as a Github Action. Moreover, it adds a test for config set.
Testing is performed as part of the snap build. It may be necessary to do it in another stage or as a one-shot service depending on how unit tests progress.
To run the tests locally:
```bash
snapcraft build unit-tests
```
> Snapped testing

- utils.go
- utils_test.go
This PR supersedes #14 
It adds a UnsetConfig function to unset a config value.
Current workaround from https://github.com/edgexfoundry/edgex-go/pull/3791:
Use [SetConfig](https://pkg.go.dev/github.com/canonical/edgex-snap-hooks#CtlCli.SetConfig) and set the config value to empty string.
> feat: add function to unset config value

- utils.go
This commit fixes an issue with ` snap set edgexfoundry env.security-proxy.tls-certificate` and `snap set edgexfoundry env.security-proxy.tls-private-key`
Using those commands currently results in failure:  `error: cannot perform the following tasks:
Run configure hook of "edgexfoundry" snap (run hook "configure": exit status 1)`
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
Note: the instructions below are also in the Snap README.md and they are being updated in a pending PR (https://github.com/edgexfoundry/edgex-go/pull/3794 )
To test this you need to get the edgex-go source and then update `/snap/local/hooks/go.mod`, adding a `replace` line at the end:
```
replace github.com/canonical/edgex-snap-hooks/v2 v2.0.5 => github.com/siggiskulason/edgex-snap-hooks/v2 v2.1.0-1
``` …
> fix(snap): add Kong Admin JWT to TLS requests

- LICENSE
This commit replaces the included license text with the original Apache 2.0 license from https://www.apache.org/licenses/LICENSE-2.0.txt
The included text specified "Dell, Inc." as copyright holder in the appendix. This was simply due to a replication error as the license was taken from another project.
> Replace with original Apache 2.0 license text

- utils.go
Fixes #15 
Error message not printed to stderr.
```
$ sudo snap install edgexfoundry --edge
edgexfoundry (edge) 2.2.0-dev.20 from Canonical✓ installed
$ sudo snap set edgexfoundry env.security-proxy.user="bad-user"
error: cannot perform the following tasks:
- Run configure hook of "edgexfoundry" snap (run hook "configure": exit status 1)
$
$
$ journalctl -n 100 -o cat | grep "bad-user"
farshid : TTY=pts/3 ; PWD=/home/farshid ; USER=root ; COMMAND=/usr/bin/snap set edgexfoundry env.security-proxy.user=bad-user
edgexfoundry:configure: error handling services: security-proxy.user expects a value containing 'username,userID,algorithm'. Example: 'me,1234,ES256' but got [bad-user]
taskrunner.go:271: [change 16494 "Run configure hook of \"edgexfoundry\" snap" task] failed: run hook "configure": …
```
> Return snapctl standard errors to caller

- Makefile
- log/init.go
- log/init_test.go
- log/log.go
- log/log_test.go
- utils.go
This PR adds a separate logging package with extended functionality.
It:
- fixes #24
- fixes #12
- fixes #29
Test by adding the following to `go.mod`:
```
replace github.com/canonical/edgex-snap-hooks/v2 => github.com/farshidtz/edgex-snap-hooks/v2 da083736dcb18258dd425431d06df0b42e96760c
```
Add to configure hook:
```
log.SetComponentName("configure")
log.Infof("info testing new library")
log.Debugf("debug testing new library")
log.Warnf("warn testing new library")
log.Errorf("err testing new library")
log.Errorf("err testing new library 2")
os.Exit(1)
```
Build and install. Logs should show:
```
$ sudo snap install --dangerous ./edgex-device-mqtt_2.2.0-dev.9_amd64.snap 
error: cannot perform the following tasks:
- Run configure hook of "edgex-device-mqtt" snap if present (run hook …
```
> Create a separate log package

- options/options.go
- options/options_test.go
- Now backward compatible, so the following should work:
```
snap set my-snap env.my-service.service.host=localhost
snap set my-snap apps.my-service.config.service.port=8080
snap set my-snap config.debug=true
```
- Replaced Info messages with Debug messages
- Rename ProcessOptions to ProcessAppConfig
Fixes #32 
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
---
Related to:
- https://github.com/canonical/edgex-snap-hooks/pull/30
> update processing when no global config

- options/options.go
- options/options_test.go
Implement a mapping of env options set in the edgexfoundry install hook to apps.*
Throw an error in other mixed configurations
- Closes #34 by disallowing other mixed options and throwing an error
- Relates to #37
> Handle mixed env legacy options

- options/options.go
Two fixes:
- Reject legacy env options only when apps and config are set
- Unset options only if they have been migrated (this is to avoid having unnecessary dangling `env: {}` config option on unset.
> Fix rejecting mixed legacy options

- log/init.go
- log/init_test.go
- options/env.go
- options/options.go
- options/options_test.go
- options/secrets-config.go
- utils.go
Fixes for #38.
Moved proxy-related code to the options package.
Added proxy options processing for TLS:
- apps.secrets-config.proxy.tls.cert
- apps.secrets-config.proxy.tls.key
- apps.secrets-config.proxy.tls.snis
Added proxy options processing for user:
- apps.secrets-config.proxy.admin.public-key
For usability purposes, the username, userid, algorithm of the single user have been hardcoded to admin, 1, ES256. This should be sufficient since we don't allow setting multiple users using snap options. The algorithm is set to ES256 rather than RS256, because it is more secure.
To avoid mixed option issues, the new namespace is now enabled after opting-in by setting `config-enabled=true`.
Add the following to go.mod:
```
replace github.com/canonical/edgex-snap-hooks/v2 => …
```
> Fix options migration, implement proxy options

- options/env.go
- options/options.go
- options/options_test.go
> Remove support for complex config keys

- options/options.go
This change is to limit config validation to config options `apps.<app>.config.<var>`, and exclude other options such as `apps.secrets-config.proxy.<var>`.
> Limit config validation to config options

- options/env.go
- options/options_test.go
- utils.go
This PR resolves https://github.com/canonical/edgex-snap-hooks/issues/52
> Remove `export` bash command to process valid .env files

- utils.go
- utils_test.go
resolves https://github.com/canonical/edgex-snap-hooks/issues/57
> Add library function for copying directory

- options/env.go
Fixes https://github.com/canonical/edgex-snap-hooks/issues/62
> Create parent directory for env file

- options/secrets-config.go
This is a temporary workaround for the issue reported at https://github.com/edgexfoundry/edgex-go/issues/4337
```
sudo rm -f /var/snap/edgexfoundry/current/secrets/security-proxy-setup/.secrets-config-user
echo "123" | sudo tee /var/snap/edgexfoundry/current/secrets/security-proxy-setup/kong-admin-jwt
snap set edgexfoundry apps.secrets-config.proxy.admin.public-key="xxx"
```
The snap logs:
```
2023-02-27T12:44:30+01:00 systemd[1]: Starting Service for snap application edgexfoundry.secrets-config-processor...
2023-02-27T12:44:30+01:00 edgexfoundry.options[37756]: Processing snap options for secrets-config
2023-02-27T12:44:30+01:00 edgexfoundry.options[37756]: proxy: Added new user
2023-02-27T12:44:30+01:00 systemd[1]: snap.edgexfoundry.secrets-config-processor.service: Deactivated …
```
> Capture output errors from secrets-config

- options/env.go
- options/options_test.go
Install device virtual (edge) and connect the config provider. 
Set a snap option (example: `snap set edgex-device-virtual config.writable-loglevel=DEBUG`)
Look for expected error: `could not process config options: failed to remove env file: unlinkat /var/snap/edgex-device-mqtt/2762/config/device-mqtt/res/device-virtual.env: read-only file system`
Build from https://github.com/edgexfoundry/device-virtual-go/pull/354
Connect the config provider.
Use:
```
$ snap set edgex-device-virtual config.writable-loglevel=DEBUG
$ cat /var/snap/edgex-device-virtual/current/config/device-virtual/overrides.env 
WRITABLE_LOGLEVEL="DEBUG"
```
> Move env file to parent directory to avoid conflict with config provider

- Makefile
- README.md
- snap/snapcraft.yaml
- snapctl/README.md
- snapctl/is-connected.go
- snapctl/is-connected_test.go
Create a UC model assertion that installs first the config provider, then device virtual (--edge).
Add appropriate connection to the gadget to connect the provider and consumer.
Install and look for expected errors: `error installing config file: open /var/snap/edgex-device-virtual/180/config/device-virtual/res/configuration.toml: read-only file system`
Build device virtual from https://github.com/edgexfoundry/device-virtual-go/pull/354
Upload to a branch and change the model assertion to use that instead.
Repeat as above and make sure the error is NOT there.
Enable debugging logs: `snap set edgex-device-virtual debug=true`
> Add snapctl wrapper to check connected interfaces
